/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 카테고리 목록 (미지정 맨 위, sortOrder 순) */
        get: operations["listCategories"];
        put?: never;
        /** 카테고리 추가 (맨 뒤) */
        post: operations["createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 카테고리 삭제 (연결된 일정·Todo는 미지정으로) */
        delete: operations["deleteCategory"];
        options?: never;
        head?: never;
        /** 카테고리 수정 (미지정은 색만) */
        patch: operations["updateCategory"];
        trace?: never;
    };
    "/categories/{id}/position": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        /** 카테고리 순서 이동 (afterId null = 미지정 바로 뒤) */
        put: operations["moveCategory"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 기간과 겹치는 일정 (시작 시각 순) */
        get: operations["listSchedules"];
        put?: never;
        /** 일정 추가 */
        post: operations["createSchedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** 일정 한 개 */
        get: operations["getSchedule"];
        put?: never;
        post?: never;
        /** 일정 삭제 */
        delete: operations["deleteSchedule"];
        options?: never;
        head?: never;
        /** 일정 수정 */
        patch: operations["updateSchedule"];
        trace?: never;
    };
    "/todos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Todo 조회 — date / from+to / completedOn 중 하나만
         * @description - date: 그날 박스. date가 오늘이면 지난 미완료 Todo도 포함 (D-029). 미완료 먼저, sortOrder 순.
         *     - from+to(+scheduled): 기간과 겹치는 Todo. scheduled=true면 time 있는 것만.
         *     - completedOn: 그날 완료한 Todo (DIARY-04).
         *     조건이 없거나 둘 이상이면 400 INVALID_QUERY.
         */
        get: operations["listTodos"];
        put?: never;
        /** Todo 추가 (맨 뒤) */
        post: operations["createTodo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/todos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Todo 한 개 */
        get: operations["getTodo"];
        put?: never;
        post?: never;
        /** Todo 삭제 */
        delete: operations["deleteTodo"];
        options?: never;
        head?: never;
        /** Todo 수정·완료·완료 취소 */
        patch: operations["updateTodo"];
        trace?: never;
    };
    "/todos/{id}/position": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        /** Todo 순서 이동 (afterId null = 맨 앞) */
        put: operations["moveTodo"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ddays": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** D-Day 목록 (sortOrder 순) */
        get: operations["listDdays"];
        put?: never;
        /** D-Day 추가 (맨 뒤, display 생략 시 countType별 기본값) */
        post: operations["createDday"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ddays/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** D-Day 한 개 */
        get: operations["getDday"];
        put?: never;
        post?: never;
        /** D-Day 삭제 */
        delete: operations["deleteDday"];
        options?: never;
        head?: never;
        /** D-Day 수정 (display 안의 필드도 보낸 것만) */
        patch: operations["updateDday"];
        trace?: never;
    };
    "/ddays/{id}/position": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        /** D-Day 순서 이동 (afterId null = 맨 앞) */
        put: operations["moveDday"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dday-marks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 기간 안에 달력에 표시할 D-Day (서버 계산, 읽기 전용) */
        get: operations["listDdayMarks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diaries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 기간 안의 일기 (날짜 순) */
        get: operations["listDiaries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diaries/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                date: string;
            };
            cookie?: never;
        };
        /** 그날 일기 */
        get: operations["getDiary"];
        /** 그날 일기 쓰기·덮어쓰기 */
        put: operations["putDiary"];
        post?: never;
        /** 그날 일기 삭제 */
        delete: operations["deleteDiary"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 메모 목록 (최근 수정 순) */
        get: operations["listMemos"];
        put?: never;
        /** 메모 추가 */
        post: operations["createMemo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** 메모 한 개 */
        get: operations["getMemo"];
        put?: never;
        post?: never;
        /** 메모 삭제 */
        delete: operations["deleteMemo"];
        options?: never;
        head?: never;
        /** 메모 수정 */
        patch: operations["updateMemo"];
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 설정 읽기 */
        get: operations["getSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 바뀐 설정만 저장 (sidebarItems는 4개 전체를 순서대로) */
        patch: operations["updateSettings"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Format: int64 */
        Id: number;
        /** @example #2F62A8 */
        Color: string;
        /**
         * @description YYYY-MM-DDTHH:mm:ss (Asia/Seoul, 시간대 표시 없음)
         * @example 2026-09-24T10:00:00
         */
        LocalDateTime: string;
        /**
         * @description HH:mm
         * @example 11:00
         */
        LocalTime: string;
        PositionRequest: {
            /**
             * Format: int64
             * @description 이 항목 바로 뒤로 이동. null = 맨 앞 (카테고리는 미지정 바로 뒤)
             */
            afterId: number | null;
        };
        /** @description RFC 9457 Problem Details + code, errors */
        Problem: {
            /** @default about:blank */
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** @enum {string} */
            code: "VALIDATION_FAILED" | "INVALID_QUERY" | "NOT_FOUND" | "CATEGORY_NAME_DUPLICATED" | "DEFAULT_CATEGORY_LOCKED" | "UNSUPPORTED_REQUEST" | "INTERNAL_ERROR";
            errors?: {
                field: string;
                message: string;
            }[];
        };
        Category: {
            id: components["schemas"]["Id"];
            name: string;
            color: components["schemas"]["Color"];
            /** @description true = 미지정 */
            readonly isDefault: boolean;
            readonly sortOrder: number;
            /** @description 연결된 일정 수 (삭제된 것 제외 */
            readonly scheduleCount: number;
            /** @description 연결된 Todo 수 (삭제된 것 제외 */
            readonly todoCount: number;
        };
        CategoryCreateRequest: {
            name: string;
            color: components["schemas"]["Color"];
        };
        CategoryUpdateRequest: {
            name?: string;
            color?: components["schemas"]["Color"];
        };
        Location: {
            name?: string | null;
            latitude?: number | null;
            longitude?: number | null;
        };
        ScheduleFields: {
            title?: string;
            allDay?: boolean;
            start?: components["schemas"]["LocalDateTime"];
            end?: components["schemas"]["LocalDateTime"];
            /**
             * Format: int64
             * @description 생략하면 미지정
             */
            categoryId?: number;
            /** @description null = 테마의 Theme2 (D-030) */
            color?: components["schemas"]["Color"] | null;
            description?: string | null;
            location?: components["schemas"]["Location"] | null;
            url?: string | null;
        };
        Schedule: components["schemas"]["ScheduleFields"] & {
            id: components["schemas"]["Id"];
        };
        ScheduleCreateRequest: components["schemas"]["ScheduleFields"] & Record<string, never>;
        ScheduleUpdateRequest: components["schemas"]["ScheduleFields"];
        /** @enum {string} */
        TodoType: "DAY" | "PERIOD" | "WEEK" | "MONTH";
        TodoTime: {
            start: components["schemas"]["LocalTime"];
            durationMinutes: number;
        };
        TodoFields: {
            title?: string;
            type?: components["schemas"]["TodoType"];
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            /** @description null = 시간 없음 (목록에만) */
            time?: components["schemas"]["TodoTime"] | null;
            /**
             * Format: int64
             * @description 생략하면 미지정
             */
            categoryId?: number;
            /** @description null = 테마의 Theme2 (D-030) */
            color?: components["schemas"]["Color"] | null;
        };
        Todo: components["schemas"]["TodoFields"] & {
            id: components["schemas"]["Id"];
            completed: boolean;
            readonly completedAt: components["schemas"]["LocalDateTime"] | null;
            readonly sortOrder: number;
            /** @description 미완료이고 endDate < 오늘 */
            readonly overdue: boolean;
        };
        TodoCreateRequest: components["schemas"]["TodoFields"] & Record<string, never>;
        TodoUpdateRequest: components["schemas"]["TodoFields"] & {
            /** @description true면 completedAt = 지금 */
            completed?: boolean;
        };
        /**
         * @description COUNTDOWN 당일=0일 / COUNTUP 당일=1일
         * @enum {string}
         */
        DdayCountType: "COUNTDOWN" | "COUNTUP";
        DdayDayOption: {
            enabled?: boolean;
            days?: number;
        };
        DdayDisplay: {
            interval?: components["schemas"]["DdayDayOption"];
            lastDays?: components["schemas"]["DdayDayOption"];
            /** @description COUNTDOWN만 */
            daily?: boolean;
            /** @description COUNTUP만 */
            yearly?: boolean;
        };
        DdayFields: {
            title?: string;
            /** Format: date */
            targetDate?: string;
            countType?: components["schemas"]["DdayCountType"];
            display?: components["schemas"]["DdayDisplay"];
        };
        Dday: components["schemas"]["DdayFields"] & {
            id: components["schemas"]["Id"];
            readonly sortOrder: number;
            readonly today: {
                value: number;
                /**
                 * @example D-1000
                 * @example D-Day
                 * @example D+30
                 */
                label: string;
            };
        };
        DdayCreateRequest: components["schemas"]["DdayFields"] & Record<string, never>;
        DdayUpdateRequest: components["schemas"]["DdayFields"];
        DdayMark: {
            /** Format: int64 */
            ddayId: number;
            /** Format: date */
            date: string;
            /**
             * @example D-900
             * @example D-Day
             * @example 100일
             * @example 1주년
             */
            label: string;
            /** @enum {string} */
            kind: "TARGET" | "INTERVAL" | "LAST_DAYS" | "DAILY" | "YEARLY";
        };
        Diary: {
            /** Format: date */
            date: string;
            content: string;
            updatedAt: components["schemas"]["LocalDateTime"];
        };
        DiaryPutRequest: {
            content: string;
        };
        Memo: {
            id: components["schemas"]["Id"];
            title: string | null;
            content: string | null;
            createdAt: components["schemas"]["LocalDateTime"];
            updatedAt: components["schemas"]["LocalDateTime"];
        };
        /** @description title과 content가 둘 다 비면(공백만 있는 것 포함) 400. 새 메모를 모두 비운 채 나가면 FE가 요청을 보내지 않는다 (D-032) */
        MemoRequest: {
            title?: string | null;
            content?: string | null;
        };
        SidebarItem: {
            /** @enum {string} */
            type: "TODO" | "DDAY" | "DIARY" | "MEMO";
            visible: boolean;
        };
        SettingsFields: {
            /** @enum {string} */
            weekStartDay?: "SUN" | "MON";
            /**
             * @description LAST = 마지막에 본 화면 (브라우저 localStorage, 서버 저장 없음)
             * @enum {string}
             */
            startView?: "MONTH" | "WEEK" | "DAY" | "LAST";
            /** @enum {string} */
            timeFormat?: "24H" | "12H";
            timetableStartHour?: number;
            timetableEndHour?: number;
            /** @enum {integer} */
            slotMinutes?: 30 | 60;
            darkMode?: boolean;
            /** @enum {string} */
            colorTheme?: "GREEN" | "BROWN" | "GRAY";
            sidebarOpen?: boolean;
            /** @description 배열 순서 = 표시 순서. 보낼 때 4개 전체 */
            sidebarItems?: components["schemas"]["SidebarItem"][];
        };
        Settings: components["schemas"]["SettingsFields"] & Record<string, never>;
        SettingsUpdateRequest: components["schemas"]["SettingsFields"];
    };
    responses: {
        /** @description 입력값 오류 (VALIDATION_FAILED) 또는 조회 조건 오류 (INVALID_QUERY) */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 없는 리소스 (NOT_FOUND) */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 요청 방식 오류 (UNSUPPORTED_REQUEST) — 405, 406, 415 등 */
        UnsupportedRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 규칙 충돌 (CATEGORY_NAME_DUPLICATED, DEFAULT_CATEGORY_LOCKED) */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        Id: number;
        /** @description 시작 날짜 (포함) */
        FromRequired: string;
        /** @description 끝 날짜 (포함). from부터 최대 62일, 넘으면 400 INVALID_QUERY (D-032) */
        ToRequired: string;
        FromOptional: string;
        ToOptional: string;
        /** @description 카테고리 필터. 여러 번 쓸 수 있음. 없으면 전체 */
        CategoryIdFilter: number[];
    };
    requestBodies: never;
    headers: {
        /** @description 만든 리소스의 주소 */
        Location: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][];
                };
            };
        };
    };
    createCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    Location: components["headers"]["Location"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
        };
    };
    deleteCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    updateCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryUpdateRequest"];
                "application/merge-patch+json": components["schemas"]["CategoryUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    moveCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PositionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listSchedules: {
        parameters: {
            query: {
                /** @description 시작 날짜 (포함) */
                from: components["parameters"]["FromRequired"];
                /** @description 끝 날짜 (포함). from부터 최대 62일, 넘으면 400 INVALID_QUERY (D-032) */
                to: components["parameters"]["ToRequired"];
                /** @description 카테고리 필터. 여러 번 쓸 수 있음. 없으면 전체 */
                categoryId?: components["parameters"]["CategoryIdFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule"][];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    createSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    Location: components["headers"]["Location"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleUpdateRequest"];
                "application/merge-patch+json": components["schemas"]["ScheduleUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    listTodos: {
        parameters: {
            query?: {
                date?: string;
                from?: components["parameters"]["FromOptional"];
                to?: components["parameters"]["ToOptional"];
                scheduled?: boolean;
                completedOn?: string;
                /** @description 카테고리 필터. 여러 번 쓸 수 있음. 없으면 전체 */
                categoryId?: components["parameters"]["CategoryIdFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"][];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    createTodo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TodoCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    Location: components["headers"]["Location"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getTodo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteTodo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateTodo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TodoUpdateRequest"];
                "application/merge-patch+json": components["schemas"]["TodoUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    moveTodo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PositionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    listDdays: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dday"][];
                };
            };
        };
    };
    createDday: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DdayCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    Location: components["headers"]["Location"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dday"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getDday: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dday"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteDday: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateDday: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DdayUpdateRequest"];
                "application/merge-patch+json": components["schemas"]["DdayUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dday"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    moveDday: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PositionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dday"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    listDdayMarks: {
        parameters: {
            query: {
                /** @description 시작 날짜 (포함) */
                from: components["parameters"]["FromRequired"];
                /** @description 끝 날짜 (포함). from부터 최대 62일, 넘으면 400 INVALID_QUERY (D-032) */
                to: components["parameters"]["ToRequired"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DdayMark"][];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    listDiaries: {
        parameters: {
            query: {
                /** @description 시작 날짜 (포함) */
                from: components["parameters"]["FromRequired"];
                /** @description 끝 날짜 (포함). from부터 최대 62일, 넘으면 400 INVALID_QUERY (D-032) */
                to: components["parameters"]["ToRequired"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Diary"][];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getDiary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Diary"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    putDiary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                date: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiaryPutRequest"];
            };
        };
        responses: {
            /** @description 덮어씀 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Diary"];
                };
            };
            /** @description 새로 씀 */
            201: {
                headers: {
                    Location: components["headers"]["Location"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Diary"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    deleteDiary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    listMemos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Memo"][];
                };
            };
        };
    };
    createMemo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    Location: components["headers"]["Location"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Memo"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getMemo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Memo"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteMemo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateMemo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoRequest"];
                "application/merge-patch+json": components["schemas"]["MemoRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Memo"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
        };
    };
    updateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdateRequest"];
                "application/merge-patch+json": components["schemas"]["SettingsUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
}
