import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Main_layout from "@/component/main/main_layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Main_layout title="gogo">
            {children}
        </Main_layout>
      </body>
    </html>
  );
}
